### ISSUE TITLE
[Bug] Need a strongly named assembly to use with signed projects

### ISSUE THREAD

**Issue by rboy1** [thomasgalliker/ObjectDumper#105]
It's recommended to publish strongly named assemblies as they can work with both signed and unsigned projects. In it's current form it can't be used with signed projects as they require a strongly named assembly. The only solution is to rebuild the project from scratch but that defeats the purpose of having nuget

**Comment by thomasgalliker** [comment]
True. 👍🏻

**Comment by thomasgalliker** [comment]
I‘ll do this as soon as the record types change is done 👍🏻

**Comment by thomasgalliker** [comment]
So, @rboy1 there is a new nuget pre-release package available, which includes assembly strong-naming. Can you use this nuget in your project and check if it works?
https://www.nuget.org/packages/ObjectDumper.NET/4.0.3-pre

Thanks for your feedback.

**Comment by rboy1** [comment]
It's working, thanks.

**Comment by thomasgalliker** [comment]
Ok cool. Thanks for testing.
