### ISSUE TITLE
[help wanted] Recurse embedded classes

### ISSUE THREAD

**Issue by sindizzy** [thomasgalliker/ObjectDumper#128]
v4.27: I got this great library working and it is really very handy. Thanks!
One question though. If I have classes within classes does the lib not dump those out?
Like in a recursive method?

If I take the dump at default options I get something like

```
  ResponseStatus: {ResponseStatus}

  ResponseContent: "[]"
```

If I manually dump out the ResponseStatus class I get

```
restDs.ResponseStatus.StatusType=OK
restDs.ResponseStatus.Errors=
restDs.ResponseStatus.Warnings=
```

if I serialize to json I get

```
  "ResponseStatus": {
    "StatusType": "OK",
    "Errors": null,
    "Warnings": null
  },
  "ResponseContent": "[]",
```
I've tried almost every option but can't seem to get the output on this embedded class.

**Comment by thomasgalliker** [comment]
What is ResponseStatus? Can I find this class somewhere to reproduce your case in a unit test?

**Comment by sindizzy** [comment]
Here are the classes. No constructors or methods. Very basic.


```
    public class RestDataset
    {
        public ResponseStatus ResponseStatus { get; set; } = null;
        public object ResponseContent { get; set; } = null;
    }
	

    public class ResponseStatus
    {
        public statusType StatusType;
        public string Errors;
        public string Warnings;
    }

    public enum statusType
    {
        OK,
        WARNING,
        ERROR,
 }

```
and the population is also very simple

```
RestDataset restDs = new RestDataset ();
restDs.ResponseStatus = new ResponseStatus { StatusType = statusType.OK };
restDs.ResponseContent = "[]";

// get a dump of all objects
//DumpOptions dumpOps = new DumpOptions();
 var strDump = ObjectDumper.Dump(restDs);
Debug.Print(strDump);
```

**Comment by thomasgalliker** [comment]
Thanks, I‘ll try to reproduce it.

**Comment by thomasgalliker** [comment]
You did create fields instead of properties in this class:
```
public class ResponseStatus
{
    public statusType StatusType;
    public string Errors;
    public string Warnings;
}
```
If you create properties instead, it will work as expected:
```
public class ResponseStatus
{
    public StatusType StatusType { get; set; }
    public string Errors { get; set; }
    public string Warnings { get; set; }
}
```
This will print as follows:
```
{RestDataset}
  ResponseStatus: {ResponseStatus}
    StatusType: StatusType.OK
    Errors: null
    Warnings: null
  ResponseContent: "[]"
```

**Comment by thomasgalliker** [comment]
It is not planned to dump fields. You should avoid public fields; use properties instead.

**Comment by sindizzy** [comment]
wow. i must have looked at my classes for days trying to figure out the differences and i totally missed that. Thanks for the help. I see my error now.

**Comment by sindizzy** [comment]
Not only that, this change helped with another outstanding bug I had unrelated to the dumper. Thank you again.

**Comment by thomasgalliker** [comment]
Ok. Always happy to help 👌🏻
