### ISSUE TITLE
DumpOptions is not passed into the  implementation constructor's.

### ISSUE THREAD

**Issue by url00** [thomasgalliker/ObjectDumper#16]
See the Dump code:
https://github.com/thomasgalliker/ObjectDumper/blob/9b0121273bce06ee66f7b3e4a0e7e9d2d42c8c75/ObjectDumper/ObjectDumper.cs#L19-L32

The parameter is never passed, so DumpOptions is always set to default.

**Comment by thomasgalliker** [comment]
Oops! I’m sorry for this. Gonna have a look into it asap.

**Comment by thomasgalliker** [comment]
#18

**Comment by thomasgalliker** [comment]
@url00 can you please check the lastest NuGet pre-release, 2.1.18332.5-pre
What do you think about the new method signature: Dump(Element, DumpStyle, DumpOptions)?
Would you keep the DumpStyle inside DumpOptions?

**Comment by url00** [comment]
First, thanks for the quick response!
Second, I feel like it's rather a semantic difference. The question is: how often does the style change?
By putting it separate as its own parameter, it suggests that it changes often.
It's not much functionally different than something like this:
`.Dump(thing, new DumpOptions { DumpStyle = DumpStyle.Console })`

I personally wouldn't have it as a separate parameter, but I don't think it's wrong.

**Comment by thomasgalliker** [comment]
As a user of the library, I would like to have DumpStyle inside the options. From the development perspective I may have to cleanup things internally when I do it like this. Anyhow, I think I gonna change it back the way it was before, just as you said:
`.Dump(thing, new DumpOptions { DumpStyle = DumpStyle.Console })`
...and a second method that simply takes the DumpStyle only:
`.Dump(thing, DumpStyle.Console)`

**Comment by thomasgalliker** [comment]
This Nuget should do it: https://www.nuget.org/packages/ObjectDumper.NET/2.1.18332.7-pre
Let me know if it works as expected, I'll release it to final then.

**Comment by url00** [comment]
Works great as far as I can tell! Thanks!
