### ISSUE TITLE
Recommendation: move ObjectDumper to global namespace

### ISSUE THREAD

**Issue by ericnewton76** [thomasgalliker/ObjectDumper#22]
First off, thanks for making this.  I usually used the original (braindead) ObjectDumper package, which worked okay but not well.

On this project though, it seems odd to include the System.Diagnostics namespace when I'm using a 3rd party library.

(And btw, Nuget maintainers keeps hinting at disallowing Nuget packages to write into System.* namespaces, reserving that only for Microsoft approved Nuget packages.  This will be enforced on publish during the validation step at some point.)

I recommend to just have the type "ObjectDumper" and "DumpOptions" in the global namespace so code like `ObjectDumper.Dump(obj)` just works.

The rest of your support could be in `namespace ObjectDumperSupport`

I say this because this is such a nice, elegantly simple package to add to any project and its immediate benefit is its ability to lay in to a lot of code by just peppering `ObjectDumper.Dump` wherever you need that.

Unfortunately, having to add the `using System.Diagnostics` to every file is cuts that down.  I say this because none of my projects use System.Diagnostics for anything... we use NLog and various other much more well thought out implementations (including this one, lol!)

Ironically the impact will be nil...

**Comment by thomasgalliker** [comment]
Done, as discussed. Closing this issue.
