### ISSUE TITLE
Recommendation: Change license to less restrictive

### ISSUE THREAD

**Issue by ericnewton76** [thomasgalliker/ObjectDumper#23]
Would you consider changing your code to be less restrictive?  I ask unfortunately after I've tweaked some of the namespaces and stuff for an upcoming PR.

Like LGPL or similar that allows for commercial use with some attribution?

I usually use Apache 2.0 or LGPL or MIT depending on how broadly I would love seeing basic building blocks of projects like this get used widespread.

**Comment by thomasgalliker** [comment]
I wonder which is the best possible dual license option for open source projects. I‘m not a capitalist, but I think people and companies which use open source projects for commercial purposes should pay a fair amount.
Do you know if Apache 2.0 or MIT license work in a dual license model? With dual I mean „free for non-commercial, paid for commercial“.

**Comment by 0xF6** [comment]
>for commercial purposes should pay a fair amount.

Oh, don't be ridiculous, o'course this is so, in an ***ideal world***.
Your code costs no more than 1-2$, really, consequently commercial companies will not strain to buy a license to use, faster and easier to use `JsonConvert.SerializeObject(...)` 😄 
So it is in your best interest to make the license more attractive and place patreon\donat-alert in `readme.md` - who wants to 'thank' you 

No, then again - this is your thing~ 🤗

**Comment by thomasgalliker** [comment]
So, if JsonConvert is the faster and easier option, what is the added value of ObjectDumper then? 1-2$ ok... I hire you 😂 If commercial companies make millions why do you think someone like me should not get compensated if they use my software?

**Comment by 0xF6** [comment]
Because the game is not worth candle, time spent on "registration" of license will be more expensive than writing custom dumper~

**Comment by thomasgalliker** [comment]
I agree, its all about tradeoffs: If your development time is less expensive than the license, write your own custom dumper.

**Comment by 0xF6** [comment]
🤗
