### ISSUE TITLE
No new line after null object

### ISSUE THREAD

**Issue by pipe01** [thomasgalliker/ObjectDumper#35]
When dumping an object with properties `Body` and `Name` using `DumpStyle.Console`, if `Body` is null there won't be a new line after that property:

```
{My.Object}
  Body: { }
    null  Name: "hello"
```

**Comment by thomasgalliker** [comment]
Ops. Thanks for reporting. Will be fixing it soon.

**Comment by thomasgalliker** [comment]
@pipe01 can you show me the My.Object you're trying to dump? What type does property Body have?

**Comment by pipe01** [comment]
[This fiddle](https://dotnetfiddle.net/mRMHpi) demonstrates the issue

**Comment by thomasgalliker** [comment]
Awww... I see. This is a classic case of code duplication. I fixed the bug for null-properties but not for null-fields. You will get an update today.

**Comment by thomasgalliker** [comment]
Now, it's also fixed for public fields:
https://www.nuget.org/packages/ObjectDumper.NET/2.3.19050.3-pre

Can you check if it solves the problem?

**Comment by pipe01** [comment]
Seems like it's fixed, thank you!
