### ISSUE TITLE
ObjectDumper produces un-compilable code

### ISSUE THREAD

**Issue by sp4rc** [thomasgalliker/ObjectDumper#54]
Consider the following code snippet where `ExecutionReport` is a type coming from the QuickFixN framework (the type definition can be found [here](https://github.com/connamara/quickfixn/blob/f75460fd4b2904860eb09ef1574e08916e3bb40c/Messages/FIX44/ExecutionReport.cs): ):

```
var executionReport = new ExecutionReport
{
    ClOrdID = new ClOrdID { Obj = "SomeString", Tag = 11 }
};

var result = ObjectDumper.Dump(executionReport, DumpStyle.CSharp);
```
Now `result` contains:
```
var dumpedReport = new ExecutionReport
{
    { 11, new ClOrdID // => No overload for method 'Add' takes 2 arguments
    {
        Obj = "SomeString",
        Tag = 11
    }
    }
};
```
In this case the `ObjectDumper` produces un-compilable code, saying `No overload for method 'Add' takes 2 arguments`. How can this be fixed?

**Comment by thomasgalliker** [comment]
As discussed, do you think you can provide a small console app with this case?

**Comment by sp4rc** [comment]
There you go: https://github.com/sp4rc/ObjectDumperBug

**Comment by thomasgalliker** [comment]
ExecutionReport is a list of KeyValuePair<int, IField> and is dumped as such. Unfortunately, the class ExecutionReport does not have an implicit conversion back from KVP to ExecutionReport. 
Maybe you can ask the Quickfix guys to implement it?

**Comment by thomasgalliker** [comment]
Any chance to check and comment my comments?

**Comment by sp4rc** [comment]
Its very unlikely that the developers of quickfixn are going to implement this. But never mind, issue can be closed
