### ISSUE TITLE
Can we dump a csharp struct?

### ISSUE THREAD

**Issue by anaselhajjaji** [thomasgalliker/ObjectDumper#61]
Example of struct:
```csharp
public struct X509ChainStatus
    {
        
        public X509ChainStatusFlags Status { get; set; }
        
        public string StatusInformation { get; set; }
    }
```

Dump a list not working, returns empty string:

```csharp
var listToDump = new List<X509ChainStatus>();
           // populate the list
            var dump = ObjectDumper.Dump(listToDump);
// dump = "System.Security.Cryptography.X509Certificates.X509ChainStatus\r\n"
```

**Comment by thomasgalliker** [comment]
Ok, interesting. I gonna reproduce it with a unit test.

**Comment by thomasgalliker** [comment]
I just verified in PR: #67: Dumping the mentioned X509ChainStatus struct works pretty well. Can you retest and let me know if it works meanwhile? (For your information: There has been a lot of change in the past, so it might also have solved this issue.
Kindly let me know if it still not works.

**Comment by thomasgalliker** [comment]
@anaselhajjaji I see if you dump an empty collection with DumpStyle.Console (default), it just prints an empty string "". Do you think this is a problem? Or how else should we print an empty collection?
