### ISSUE TITLE
Dump to CSharp - decimals depands on the culture

### ISSUE THREAD

**Issue by loictr** [thomasgalliker/ObjectDumper#70]
Hi,

I work on a computer with a French windows. 
While debugging, when I dump an object with decimal properties, I get decimals separator as a comma (',') which is not valid in C#, it should be a point ('.').

`MyProp = 2,05m`
should be
`MyProp = 2.05m`

**Comment by thomasgalliker** [comment]
That's indeed very bad. I fixed it in PR #71 
I'll let you know if a new nuget pre-release package is available.

**Comment by thomasgalliker** [comment]
Nuget version [3.0.20243.1-pre](https://www.nuget.org/packages/ObjectDumper.NET/3.0.20243.1-pre) contains the bug fixes for the reported culture problem. Can you give it a try, @loictr ?

**Comment by loictr** [comment]
@thomasgalliker I tried it yesterday, it seems fixed, thanks !
