### ISSUE TITLE
Track already dumped objects

### ISSUE THREAD

**Issue by thomasgalliker** [thomasgalliker/ObjectDumper#75]
In order to avoid infinite recursions when dumping circularly referenced objects, we need to track the dumped object‘s hashes in a list. The current implementation does not work properly. 

See DumpedObjects for impl. reference:
https://github.com/vmelamed/vm/blob/cc383352c8a5480e763847a4f3469e1ed244e0ca/Aspects/Diagnostics/ObjectTextDumper/src/Implementation/DumpedObject.cs

**Comment by dzmitry-lahoda** [comment]
depth?

**Comment by dzmitry-lahoda** [comment]
LIMIT DEPTH IS MUST SAFE DEFAULT!!!!!

**Comment by thomasgalliker** [comment]
The pre-release nuget with this feature (and the rest of this weekend’s improvements) is ready here: https://www.nuget.org/packages/ObjectDumper.NET/3.1.21144.2-pre

IBAN for donations: CH26 8080 8009 3161 7665 0
