### ISSUE TITLE
yaml output

### ISSUE THREAD

**Issue by dzmitry-lahoda** [thomasgalliker/ObjectDumper#77]
will donate 20 USD for that option (one time, not continuous)

**Comment by thomasgalliker** [comment]
Are you looking for something like that? https://github.com/aaubry/YamlDotNet

**Comment by dzmitry-lahoda** [comment]
i did object dumpler previosly. yaml is simple. so either generate manually or by embedding one cs class into dumpler or assembly merge. but NOT dependency onto lib (no late binding)

**Comment by thomasgalliker** [comment]
Yes, but it seems to already exist (see here: https://www.nuget.org/packages/YamlDotNet/). So why should I invest time to create something that already exists :) Pull requests are welcome.

**Comment by dzmitry-lahoda** [comment]
if you will consider adding donate button in Polkadot DOT wallet, not for YAML, will donate here amount equal to 30 USD.

btw, Powershell also ignored YAML support a lot (not sure why). Problem with existing dlls as they make deps heavy, while dumper (and pwsh) should have yaml build in to easy of use in scripts.
