### ISSUE TITLE
Provide an extension method that Dump everything

### ISSUE THREAD

**Issue by doggy8088** [thomasgalliker/ObjectDumper#78]
The usage is something like [this](https://github.com/lassevk/ObjectDumper/blob/main/src/ObjectDumper/ObjectDumperExtensions.cs#L186-L200).

**Comment by thomasgalliker** [comment]
What do you mean with „dump everything“? When you call ObjectDumper.Dump(persons, DumpStyle.CSharp) it dumps persons to string.

**Comment by doggy8088** [comment]
I mean use `persons.Dump(DumpStyle.CSharp)` instead of `ObjectDumper.Dump(persons, DumpStyle.CSharp)`.

**Comment by thomasgalliker** [comment]
Ah ok. Yes, thats pretty useful.

**Comment by thomasgalliker** [comment]
Can you have a look at this PR please: #79

**Comment by doggy8088** [comment]
I reviewed. LGTM 👍

**Comment by thomasgalliker** [comment]
The pre-release nuget with this feature (and the rest of this weekend’s improvements) is ready here: https://www.nuget.org/packages/ObjectDumper.NET/3.1.21144.2-pre

**Comment by doggy8088** [comment]
@thomasgalliker When will you release v3.1?

**Comment by thomasgalliker** [comment]
Oughh. Good question. Did you do some tests with it in your software? I think its stable enough to release it to production soon. I‘ll gonna do it when I‘m back in the office.

**Comment by doggy8088** [comment]
It works perfectly. 👍
