### ISSUE TITLE
It doesn't Dump Fields and Private's??? 

### ISSUE THREAD

**Issue by wh0am15533** [thomasgalliker/ObjectDumper#81]

**Comment by thomasgalliker** [comment]
Unfortunately only properties so far. The goal is to generate compilable code.

**Comment by wh0am15533** [comment]
You should at least leave the option open to the user. Disable it if the user is dumping to recompile, but for examination purposes you should leave it open.  I have a private dumper that dumps everything and serializes into a nice XML that can be viewed hierarchical for dumping games. I can see your point though if your focus is on generating compilable code. Nice work otherwise!

**Comment by thomasgalliker** [comment]
That is indeed a brilliant idea. Dont get me wrong 😇 You‘re just the first reqesting for it. I will keep this idea in the back of my head. The only problem is the available time 😎
