### ISSUE TITLE
C:\src\github\thomasgalliker\ObjectDumper\ObjectDumper.Shared\ObjectDumper.cs:21

### ISSUE THREAD

**Issue by humanbeinc** [thomasgalliker/ObjectDumper#9]
NullReferenceException when using default (= NULL) options.

**Comment by thomasgalliker** [comment]
Thanks for reporting. I fixed this in Nuget Package 1.0.4 (https://www.nuget.org/packages/ObjectDumper.NET/1.0.4). Can you try & give some feedback, please?
