### ISSUE TITLE
[Bug] Cannot Work

### ISSUE THREAD

**Issue by GDdark** [thomasgalliker/ObjectDumper#91]
It's a great thing. but I'm having some trouble
I install this library and run the sample. And there were no details on the console
![image](https://user-images.githubusercontent.com/15982894/143378139-3348c211-e9ce-4d12-a5b6-c63858ed1abe.png)

I don't know if I'm using it incorrectly

OS：Macos 11.6
IDE：Rider

**Comment by GDdark** [comment]
It seems I didn't set class as public.
finally it works.

**Comment by thomasgalliker** [comment]
Awesome. If there is anything I can help you with, let me know.
