### ISSUE TITLE
[Enhancement] IEnumerable can display optimization

### ISSUE THREAD

**Issue by HZ-GeLiang** [thomasgalliker/ObjectDumper#94]
## Summary
Current program output  IEnumerable  is ...   
I would like to know what type and number of variables this variable is, not IEnumerable
while   visualStuido   debugger,  I can see the number and types of lEnumerable from the quick monitor panel

![image](https://user-images.githubusercontent.com/16562680/160743379-d1b473ed-92b5-49e5-b1c3-bc45fd00594a.png)

![image](https://user-images.githubusercontent.com/16562680/160743378-81999ac4-93f4-4105-b34c-7b7c9e5da800.png)

**Comment by thomasgalliker** [comment]
Dear @HZ-GeLiang. Nice idea. I can look into it or did you already start working on it?

**Comment by thomasgalliker** [comment]
This change does only affect DumpStyle.Console. It now prints `{TypeName, Count=123}` for IEnumerables and `{ArrayElementType[123]}` for arrays. Hope this helps.

Can you check the latest nuget pre-release, @HZ-GeLiang and let me know if this helps?
Thanks for reporting this + have a good day!
